apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
  namespace: kestra
spec:
  project: default
  sources:
    - chart: kestra
      repoURL: https://helm.kestra.io/
      targetRevision: 0.22.4
      # helm:
      #   valueFiles:
      #     - values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: kestra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

