# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kestra-auto
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     - chart: kestra
#       repoURL: https://helm.kestra.io/
#       targetRevision: 0.22.4
#       helm:
#         valueFiles:
#           - $values/manifests/values/values.yaml
#     - repoURL: https://github.com/hlengoc/argocd-infra.git
#       targetRevision: main
#       ref: values
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kestra
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra-custom
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kestra
      repoURL: https://helm.kestra.io/
      targetRevision: 0.22.4
      helm:
        releaseName: kestra
        valueFiles:
          - $values/manifests/values/kestra-values.yaml
        values: |
          image:
            image: asia-southeast1-docker.pkg.dev/fpt-dev/kestra-repo/kestra-custom
            tag: v0.0.7
          service:
            type: LoadBalancer
    - repoURL: https://github.com/hlengoc/argocd-infra.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kestra-custom

