apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra-auto
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kestra
      repoURL: https://helm.kestra.io/
      targetRevision: 0.22.4
      helm:
        valueFiles:
          - $values/manifests/values/values.yaml
    - repoURL: https://github.com/hlengoc/argocd-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kestra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


