apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: secret-key
    remoteRef:
      key: k8s-secret

  - secretKey: .env
    remoteRef:
      key: db-config  # Another secret if needed