apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress-nginx
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - frontend.haile.click
    secretName: frontend-tls
  rules:
  - host: frontend.haile.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80