apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: fpt-dev
      auth:
        workloadIdentity:
          clusterLocation: asia-southeast1-a
          clusterName: cluster-1
          serviceAccountRef:
            name: eso-secrets-sa